---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ilm-policy
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  ilm_policy.json: |-
      {
        "policy": {
          "phases": {
            "hot": {
              "actions": {
                "rollover": {
                  "max_age": "1h",
                  "max_size": "2M"
                }
              }
            },
            "delete": {
              "min_age": "30d",
              "actions": {
                "delete": {}
              }
            },
            "warm": {
              "actions": {
                "allocate": {
                  "number_of_replicas": 1
                },
                "forcemerge": {
                  "max_num_segments": 1
                },
                "shrink": {
                  "number_of_shards": 1
                }
              }
            }
          }
        }
      }
