apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: true

    monitoring:
      enabled: true
      elasticsearch:
        username: kibana
        password: password
    http:
      enabled: true
      port: 5069
    processors:
      - add_cloud_metadata:
      - add_fields:   
          target: ''
          fields:                                               
            k8s_cluster: cluster
            k8s_environment: dev
    setup.template:                                           
      overwrite: true                                         
      settings:                                                                                                              
        index.number_of_shards: 1                             
        index.number_of_replicas: 2                           
    setup.ilm:                                                
      enabled: true                                           
      rollover_alias: "metricbeat"
      policy_name: "metricbeat"                                   
      policy_file: "/etc/metricbeat_ilm_policy.json"
      overwrite: true
    output.elasticsearch:    
      hosts: ["https://elastic-es-http.default.svc.cluster.local:9200"]
      ssl.verification_mode: none
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `kube-system` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - state_cronjob
        - state_resourcequota
        # Uncomment this to get k8s events:
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics:8080"]
