---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: true

    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    monitoring:
      enabled: true
      elasticsearch:
        username: kibana
        password: password
    http:
      enabled: true
      port: 5068
    processors:
      - add_cloud_metadata:
      - add_fields:   
          target: ''
          fields:                                               
            k8s_cluster: cluster
            k8s_environment: dev

    setup.template:                                           
      overwrite: true                                         
      settings:                                                                                                              
        index.number_of_shards: 1                             
        index.number_of_replicas: 2                           
    setup.ilm:                                                
      enabled: true                                           
      rollover_alias: "metricbeat"
      policy_name: "metricbeat"                                   
      policy_file: "/etc/metricbeat_ilm_policy.json"
      overwrite: true
    output.elasticsearch:    
      hosts: ["https://elastic-es-http.default.svc.cluster.local:9200"]
      ssl.verification_mode: none
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  system.yml: |-
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        #- core
        #- diskio
        #- socket
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      hosts: ["localhost:10255"]
      # If using Red Hat OpenShift remove the previous hosts entry and 
      # uncomment these settings:
      #hosts: ["https://${HOSTNAME}:10250"]
      #bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #ssl.certificate_authorities:
        #- /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
    - module: kubernetes
      metricsets:
        - proxy
      period: 10s
      host: ${NODE_NAME}
      hosts: ["localhost:10249"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-ilm-policy
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  ilm_policy.json: |-
      {
        "policy": {
          "phases": {
            "hot": {
              "actions": {
                "rollover": {
                  "max_age": "1h",
                  "max_size": "2M"
                }
              }
            },
            "delete": {
              "min_age": "30d",
              "actions": {
                "delete": {}
              }
            },
            "warm": {
              "actions": {
                "allocate": {
                  "number_of_replicas": 1
                },
                "forcemerge": {
                  "max_num_segments": 1
                },
                "shrink": {
                  "number_of_shards": 1
                }
              }
            }
          }
        }
      }
