---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.5.2
  image: mintel/eck-elasticsearch:7.5.2-0
  secureSettings:
  - secretName: s3-credentials
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1
  nodeSets:
  - name: main
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: false
      s3.client.default.endpoint: minio.monitoring.svc.cluster.local:9000
      s3.client.default.protocol: http
      s3.client.default.path_style_access: true
      xpack.ml.enabled: false
      xpack.monitoring.enabled: true
      xpack.monitoring.collection.enabled: true
      xpack.security.authc.anonymous.username: anonymous_user 
      xpack.security.authc.anonymous.roles: superuser
      xpack.security.authc.anonymous.authz_exception: true

    podTemplate:
      metadata:
        labels:
          logformat: json
        annotations:
          roll: "2"
      spec:
        securityContext:
          runAsUser: 1000     
          fsGroup: 1000
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          resources:
            requests:
              memory: 1Gi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 0.5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
