---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-config
  namespace: kube-system
  labels:
    k8s-app: auditbeat
data:
  auditbeat.yml: |-
    auditbeat.config.modules:
      # Mounted `auditbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: true

    monitoring:
      enabled: true
      elasticsearch:
        username: kibana
        password: password
    http:
      enabled: true
      port: 5067

    processors:
      - add_cloud_metadata:
      - add_fields:   
          target: ''
          fields:                                               
            k8s_cluster: cluster
            k8s_environment: dev

    setup.template:                                           
      overwrite: true                                         
      settings:                                                                                                              
        index.number_of_shards: 1                             
        index.number_of_replicas: 2                           

    setup.ilm:                                                
      enabled: true                                           
      rollover_alias: "auditbeat"
      policy_name: "auditbeat"                                   
      policy_file: "/etc/auditbeat_ilm_policy.json"
      overwrite: true
    output.elasticsearch:    
      hosts: ["https://elastic-es-http.default.svc.cluster.local:9200"]
      ssl.verification_mode: none

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-ilm-policy
  namespace: kube-system
  labels:
    k8s-app: auditbeat
data:
  ilm_policy.json: |-
      {
        "policy": {
          "phases": {
            "hot": {
              "actions": {
                "rollover": {
                  "max_age": "1h",
                  "max_size": "2M"
                }
              }
            },
            "delete": {
              "min_age": "30d",
              "actions": {
                "delete": {}
              }
            },
            "warm": {
              "actions": {
                "allocate": {
                  "number_of_replicas": 1
                },
                "forcemerge": {
                  "max_num_segments": 1
                },
                "shrink": {
                  "number_of_shards": 1
                }
              }
            }
          }
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-daemonset-modules
  namespace: kube-system
  labels:
    k8s-app: auditbeat
data:
  system.yml: |-
    - module: file_integrity
      paths:
      - /hostfs/bin
      - /hostfs/usr/bin
      - /hostfs/sbin
      - /hostfs/usr/sbin
      - /hostfs/etc
      exclude_files:
      - '(?i)\.sw[nop]$'
      - '~$'
      - '/\.git($|/)'
      scan_at_start: true
      scan_rate_per_sec: 50 MiB
      max_file_size: 100 MiB
      hash_types: [sha1]
      recursive: true
